import { DemoPersona } from './types';

export const DEMO_PERSONAS: DemoPersona[] = [
  {
    id: 'marie',
    nom: 'Marie',
    age: '65 ans',
    girAttendu: 6,
    scenario: 'Active, légère arthrose genou. Veut prévenir les chutes.',
    emoji: '👩',
    profil: {
      respondant: 'patient',
      age: '60-70',
      sexe: 'femme',
      coherence: 0,
      orientation: 0,
      mobilite: 1,
      deplacementExterieur: 0,
      transferts: 0,
      toilette: 0,
      habillage: 0,
      alimentation: 0,
      elimination: 0,
      communication: 0,
      situationRecente: 0,
      priorites: ['aide_marche', 'salle_de_bain'],
    },
  },
  {
    id: 'jean',
    nom: 'Jean',
    age: '74 ans',
    girAttendu: 5,
    scenario: 'Essoufflement à la marche, vit seul. Difficulté dans la baignoire.',
    emoji: '👨',
    profil: {
      respondant: 'patient',
      age: '71-80',
      sexe: 'homme',
      coherence: 0,
      orientation: 0,
      mobilite: 1,
      deplacementExterieur: 1,
      transferts: 1,
      toilette: 1,
      habillage: 0,
      alimentation: 0,
      elimination: 0,
      communication: 0,
      situationRecente: 0,
      priorites: ['aide_marche', 'salle_de_bain', 'aides_techniques'],
    },
  },
  {
    id: 'francoise',
    nom: 'Françoise',
    age: '78 ans',
    girAttendu: 4,
    scenario: 'Retour d\'hospitalisation (col du fémur). Aidant : sa fille.',
    emoji: '👵',
    profil: {
      respondant: 'aidant',
      age: '71-80',
      sexe: 'femme',
      coherence: 0,
      orientation: 0,
      mobilite: 2,
      deplacementExterieur: 1,
      transferts: 2,
      toilette: 1,
      habillage: 1,
      alimentation: 0,
      elimination: 1,
      communication: 0,
      situationRecente: 2,
      priorites: ['aide_marche', 'chambre', 'toilettes'],
    },
  },
  {
    id: 'robert',
    nom: 'Robert',
    age: '82 ans',
    girAttendu: 3,
    scenario: 'Parkinson stade modéré. Chutes fréquentes. Protections jour.',
    emoji: '🧓',
    profil: {
      respondant: 'aidant',
      age: '81-90',
      sexe: 'homme',
      coherence: 1,
      orientation: 1,
      mobilite: 2,
      deplacementExterieur: 2,
      transferts: 2,
      toilette: 2,
      habillage: 1,
      alimentation: 1,
      elimination: 2,
      communication: 1,
      situationRecente: 1,
      priorites: ['fauteuils', 'chambre', 'aides_techniques'],
    },
  },
  {
    id: 'simone',
    nom: 'Simone',
    age: '86 ans',
    girAttendu: 2,
    scenario: 'AVC récent, hémiplégie gauche. Alitée la plupart du temps.',
    emoji: '👴',
    profil: {
      respondant: 'aidant',
      age: '81-90',
      sexe: 'femme',
      coherence: 1,
      orientation: 1,
      mobilite: 3,
      deplacementExterieur: 2,
      transferts: 2,
      toilette: 2,
      habillage: 2,
      alimentation: 1,
      elimination: 3,
      communication: 1,
      situationRecente: 2,
      priorites: ['chambre', 'fauteuils', 'toilettes'],
    },
  },
  {
    id: 'andre',
    nom: 'André',
    age: '90 ans',
    girAttendu: 1,
    scenario: 'Démence avancée, grabataire. Aidant : son fils. Ordonnance complète.',
    emoji: '🧑‍⚕️',
    profil: {
      respondant: 'aidant',
      age: '90+',
      sexe: 'homme',
      coherence: 2,
      orientation: 2,
      mobilite: 3,
      deplacementExterieur: 2,
      transferts: 2,
      toilette: 2,
      habillage: 2,
      alimentation: 2,
      elimination: 3,
      communication: 2,
      situationRecente: 3,
      priorites: ['chambre', 'fauteuils', 'aides_techniques'],
    },
  },
];
